Plug 'elzr/vim-json'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
Plug 'crusoexia/vim-dracula'
Plug 'altercation/vim-colors-solarized'
Plug 'whatyouhide/vim-gotham'
Plug 'sickill/vim-monokai'
Plug 'derekwyatt/vim-scala'
Plug 'klen/python-mode'
Plug 'Valloric/YouCompleteMe'
Plug 'Raimondi/delimitMate'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'lukaszb/vim-web-indent'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
